#ifndef DEFINES_H
#define DEFINES_H

// **VERSION TOGGLES ARE FOR DEVELOPMENT, THEY ARE INCOMPLETE, ENABLING WILL NOT LEAD TO STANDARD VERSIONS OF THE COMPILER**
#define Ver0_1_0

#endif // DEFINES_H
